### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zanac** [RetroPie/SDL-mirror#10]
./configure --enable-video-mali --prefix=/usr --disable-video-x11 --disable-x11-shared --disable-video-rpi --disable-video-x11-xshape --disable-video-x11-scrnsaver --disable-video-x11-xrandr --disable-video-x11-xinput --disable-video-x11-xinerama --disable-video-x11-vm --disable-video-vulkan

/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c: In function 'MALI_GLES_LoadLibrary':
/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c:33:12: error: too few arguments to function 'SDL_EGL_LoadLibrary'
     return SDL_EGL_LoadLibrary(_this, path, EGL_DEFAULT_DISPLAY);
            ^
In file included from /home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.h:29:0,
                 from /home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c:25:
/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/../SDL_egl_c.h:97:12: note: declared here
 extern int SDL_EGL_LoadLibrary(_THIS, const char *path, NativeDisplayType native_display, EGLenum platform);
            ^
In file included from /home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.h:29:0,
                 from /home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c:25:
/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c: At top level:
/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c:37:25: error: conflicting types for 'MALI_GLES_SwapWindow'
 SDL_EGL_SwapWindow_impl(MALI)
                         ^
/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/../SDL_egl_c.h:119:1: note: in definition of macro 'SDL_EGL_SwapWindow_impl'
 BACKEND ## _GLES_SwapWindow(_THIS, SDL_Window * window) \
 ^
In file included from /home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c:25:0:
/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.h:41:13: note: previous declaration of 'MALI_GLES_SwapWindow' was here
 extern void MALI_GLES_SwapWindow(_THIS, SDL_Window * window);
             ^
/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c: In function 'MALI_GLES_LoadLibrary':
/home/user/sdl_mali/SDL-mirror/src/video/mali-fbdev/SDL_maliopengles.c:34:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:578: recipe for target 'build/SDL_maliopengles.lo' failed
make: *** [build/SDL_maliopengles.lo] Error 1

**Comment by joolswills** [comment]
This fork is specifically for RetroPie -are you having a problem building on retropie or standalone? You also don't say which branch you are using or hardware, or system os. Cannot advise without information.

**Comment by zanac** [comment]
uname -a
Linux debian-armhf 3.2.0-4-vexpress #1 SMP Debian 3.2.51-1 armv7l GNU/Linux

with mali binary blob and right mali egl/gl/egl2 headers.

I'm bulding with Debian ARMHF, I'm porting SDL2 on a Pandora Arcade Box.

I ported a lot of software that embedded that use mali binary blobs, I know how to use mali EGL headers and libMali.so.... I think that there is an error in the branch, in effect:
SDL_EGL_LoadLibrary(_this, path, EGL_DEFAULT_DISPLAY);

Why not SDL_EGL_LoadLibrary(_this, path, EGL_DEFAULT_DISPLAY, 0);  ?

It's a problem of the branch, I'm pretty sure....

**Comment by joolswills** [comment]
You still don't say which branch you are using.

**Comment by zanac** [comment]
git clone -b mali https://github.com/RetroPie/SDL-mirror.git

**Comment by joolswills** [comment]
that is not a branch we use - likely it was a test/development branch. RetroPie currently uses mali-2.0.6 branch. This repo is not designed for standalone compilation but is part of retropie.

**Comment by joolswills** [comment]
Infact there is no `mali` branch in this repository. 

```
git clone -b mali https://github.com/RetroPie/SDL-mirror.git
Cloning into 'SDL-mirror'...
fatal: Remote branch mali not found in upstream origin
```

**Comment by zanac** [comment]
Sorry that's right, i compiled with branch mali-2.0.7, i try 2.0.6 branch as your suggestion.

**Comment by joolswills** [comment]
2.0.7 is not ready yet. Sorry, but I cannot offer further support on this fork outside of RetroPie issues.

**Comment by joolswills** [comment]
2.0.7 wasn't working as I rebased the patches on top of upstream from an out of date local branch. I hadn't gotten around to testing it as I did it quickly the other day in preparation for testing before updating retropie. I have just redone the branch and it may work now (you will need to do a fresh checkout though). I can't help further - and the branch may be removed in the future also.
