### ISSUE TITLE
Amibery Upgrade Issue

### ISSUE THREAD

**Issue by PotNoodleMan** [RetroPie/SDL-mirror#14]
I’m trying to upgrade Amiberry v2.24b12 to v2.25 and encounter the following error when trying to update ‘from source’ in the retroarch menus. I am running Stretch on Raspberry Pi 3.
Error: ‘Error running ‘git clone -- recursive -- depth 1........’- returned 128
Screenshot of error is attached.
I have posted to the Amiberry Github page and have been advised that its a Retropie issue.

Thanks for any assistance in advance!

![58462602-9277eb00-8175-11e9-8703-c17d28e0f5dc 1](https://user-images.githubusercontent.com/51078397/59971243-89830980-95bb-11e9-94f9-922017ec6185.png)

**Comment by joolswills** [comment]
This is the wrong place. Please use the retropie forum on our main site. The error is likely due to a faulty net connection.

**Comment by joolswills** [comment]
https://retropie.org.uk/forum/
